theme = 'hugo-theme-reimu'

defaultContentLanguage = 'zh-CN'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []
[languages]
    [languages.zh-CN]
        disabled = false
        languageCode = 'zh-CN'
        languageDirection = 'ltr'
        title = "领域展开"
        languageName = '简体中文'
        weight = 1

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'